api:
  similarIds:
    base-url: http://simulado:80
  productDetail:
    base-url: http://simulado:80
    
server:
  port: 5000

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
    instances:
      productSimilarityService:
        baseConfig: default

springdoc:
  swagger-ui:
    urls:
      - name: “SimilarProducts API”
        url: /openapi.yml